name: checks
on: [push]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Check Go format
        run: test -z "$(gofmt -l -e ${{ github.workspace }} | tee /dev/stderr)"
